# Generated by Django 3.0.14 on 2022-05-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HVACtodo', '0002_auto_20220509_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='tasks',
            new_name='votes',
        ),
    ]
