# Generated by Django 3.0.14 on 2022-05-12 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HVACtodo', '0003_auto_20220511_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
