# Generated by Django 3.0.14 on 2022-05-18 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HVACtodo', '0004_remove_choice_votes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
